name: categorias_grpc
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'


dependencies:
  grpc: ^3.0.0
  protoc_plugin: ^20.0.0-nullsafety.1
  protobuf: ^2.0.0
  hive: ^2.0.4
  configurable: ^1.0.5
  dotenv: ^3.0.0
  riverpod: ^0.14.0
  postgres: ^2.3.1
  dbcrypt: ^2.0.0
  intl: ^0.17.0
  dartx: ^0.7.1
dependency_overrides:
  protobuf:
    git: https://github.com/Dacotas11/andy_protobuf
  protoc_plugin:
    git: https://github.com/Dacotas11/andy_protoc
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
